# [claude-code] Calendar points. Generated by Claude Code from the
# temporal-things design (2026-08-04), then implemented step by step:
# constructors and validation (step 1), composition, every/3, and the
# readers (step 2), vocabulary numbering for the set layer (step 3).
# Extracted from the s7r app into the zocam library on
# 2026-08-04. No stubs remain in this module.
defmodule Zocam.Point do
  @moduledoc """
  A calendar point: a concrete or abstract "thing about time".

  A point is a pair of a **scope** and a **chain**:

  - The scope is the cycle in which the point repeats. `"May"` repeats
    each year, so its scope is `:year`. `"May 2026"` does not repeat:
    its scope is `:absolute`.
  - The chain is a list of valued segments. It starts directly under
    the scope and descends, one unit at a time, to a **grain** (the
    size of what the point names).

  Concrete and abstract are not two types. They are one field: a point
  is concrete exactly when its scope is `:absolute`.

  ## The unit graph

  Chains must follow the edges of this graph. The week branch is a
  sibling of the month branch: weeks do not nest in months or years.

      :absolute ── year ──┬── month ── day ────┬── time
                          │                    │
                          └── week(1..53) ── weekday
                                               │
      :week (cycle) ────────────── weekday ────┴── time

  Examples:

      "May"                  %Point{scope: :year,     chain: [month: :may]}
      "May 2026"             %Point{scope: :absolute, chain: [year: 2026, month: :may]}
      "the 23rd"             %Point{scope: :month,    chain: [day: 23]}
      "15:00"                %Point{scope: :day,      chain: [time: ~T[15:00:00]]}
      "a Wednesday"          %Point{scope: :week,     chain: [weekday: :wednesday]}
      "first Wed of Jan"     %Point{scope: :year,     chain: [month: :january, day: {:nth, 1, :wednesday}]}

  ## Composition

  `compose/2` concatenates two chains. It is defined exactly when the
  inner point repeats once per unit of what the outer point names:
  the inner scope must be a plain cycle of the outer grain class (an
  `{:every, ...}` inner repeats less often, so it is out). This is
  composition of arrows in a category: units are the objects, points
  are the arrows, and two arrows compose only where they meet.

  When the guard fails, the meaning is usually a *set*, not a point.
  `compose(may, at_15_00)` fails because the day is free between month
  and time; the error hint names the escape hatch:
  `Zocam.Span.intersection/1` ("15:00 of every day of May").

  ## Denotation

  A point denotes one grain-sized interval per instance of its scope
  cycle. `Zocam.Span.of/1` lifts a point into the set algebra,
  where intervals, steps, and the set operators live.

  This module is pure: no timezone, no Timex. The calendar meets the
  real timeline only in `Zocam.Span.ground/3`.
  """

  use TypedStruct

  # [claude-code] Calendar vocabulary. Full-name atoms, defined HERE:
  # since timables/0 narrowed (2026-08-04), the linear kernel is
  # calendar-free, so the calendar layer owns its own vocabulary. One
  # canonical definition, never two, for the semantically same thing.
  @type weekday :: :monday | :tuesday | :wednesday | :thursday | :friday | :saturday | :sunday
  @type month ::
          :january
          | :february
          | :march
          | :april
          | :may
          | :june
          | :july
          | :august
          | :september
          | :october
          | :november
          | :december

  # [claude-code] Units and their classes. A unit is a node of the
  # graph. Its class is the span size it names: weekday and day are
  # different nodes with the same class (:day), which is why
  # "a Wednesday" composes with "15:00".
  @type unit :: :year | :month | :week | :day | :weekday | :time
  @type grain_class :: :year | :month | :week | :day | :time

  # [claude-code] Scopes. A plain cycle repeats every instance.
  # {:every, k, cycle, anchor} repeats every k-th instance of the
  # cycle, counted from the instance that contains the anchor date.
  # This carries fortnights: "every other Wednesday" is a :week point
  # re-scoped with k = 2. The instances keep the size of the base
  # cycle (every 2nd week is still one week long, not two).
  @type cycle :: :year | :month | :week | :day
  @type scope :: :absolute | cycle() | {:every, pos_integer(), cycle(), Date.t()}

  # [claude-code] Chain segments. A day slot takes a day number
  # (negative counts from the month end: -1 is the last day), or an
  # ordinal weekday selector. A day number measures into the month,
  # so it clamps on overflow (policy below). An ordinal selects, so a
  # missing ordinal skips: {:nth, 5, :wednesday} names nothing in a
  # four-Wednesday month and stays distinct from {:nth, -1, ...}.
  @type nth_weekday :: {:nth, 1..5 | -1, weekday()}
  @type day_index :: 1..31 | -31..-1
  @type segment ::
          {:year, integer()}
          | {:month, month()}
          | {:week, 1..53}
          | {:day, day_index() | nth_weekday()}
          | {:weekday, weekday()}
          | {:time, Time.t()}
  @type chain :: [segment(), ...]

  # [claude-code] Overflow policy for day numbers that a short month
  # cannot hold. :clamp (default) moves to the month end: "the 31st"
  # fires on Feb 28. :skip drops the instance: "Feb 29" fires only in
  # leap years.
  @type overflow :: :clamp | :skip

  # [claude-code] ComposeError: the typed failure of compose/2.
  # reason :grain_gap  - same branch, but units skip a level
  #                      ("May" + "15:00": day is free in the middle).
  # reason :cross_cycle - no directed path joins the branches
  #                      ("2026" + "a Wednesday": weeks do not nest).
  # reason :invalid    - the inner point cannot sit below the outer
  #                      at all (repeated or backward unit:
  #                      "May of June").
  # reason :anchored   - the inner scope is {:every, k, cycle, anchor}.
  #                      A chain has no place for the phase, so a
  #                      composed result would silently drop it.
  # The hint holds a runnable repair, e.g. the Span.intersection call
  # that builds the set the caller probably meant.
  defmodule ComposeError do
    @moduledoc "Raised (or returned) when two points do not compose."
    defexception [:reason, :left, :right, :hint, :message]

    @type reason :: :grain_gap | :cross_cycle | :invalid | :anchored

    @type t :: %__MODULE__{
            reason: reason(),
            left: Zocam.Point.t(),
            right: Zocam.Point.t(),
            hint: String.t(),
            message: String.t()
          }
  end

  # [claude-code]
  typedstruct enforce: true do
    @typedoc "A calendar point: a scope and a contiguous chain."
    field :scope, scope()
    field :chain, chain()
    field :overflow, overflow(), default: :clamp
  end

  # [claude-code] Vocabulary constants. These lists spell out the
  # types above one time at runtime. The constructor guards and the
  # validation walk both read them, so the two can not drift apart.
  @months [
    :january,
    :february,
    :march,
    :april,
    :may,
    :june,
    :july,
    :august,
    :september,
    :october,
    :november,
    :december
  ]
  @weekdays [:monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday]
  @cycles [:year, :month, :week, :day]

  # [claude-code]
  @doc """
  Build a point and validate every invariant the types cannot hold:
  the chain is non-empty, starts directly under the scope, follows the
  unit graph edges without gaps, and every value is in range.

  This is the single validation walk. All other functions trust it,
  so build points with `new!/1` or the per-unit constructors, never
  with raw structs.
  """
  @spec new!(scope: scope(), chain: chain(), overflow: overflow()) :: t()
  def new!(opts) when is_list(opts) do
    scope = Keyword.fetch!(opts, :scope)
    chain = Keyword.fetch!(opts, :chain)
    overflow = Keyword.get(opts, :overflow, :clamp)

    validate_scope!(scope)
    validate_overflow!(overflow)
    validate_chain!(scope, chain)

    %__MODULE__{scope: scope, chain: chain, overflow: overflow}
  end

  # [claude-code] Per-unit constructors. Each constructor pairs a
  # unit value with the smallest scope in which that value repeats.
  # The success clause spells the vocabulary in its guard; the
  # fallback clause turns a wrong value into a teaching ArgumentError
  # instead of a FunctionClauseError. Trade-off: the fallback makes
  # the function accept every term, so the Elixir type checker does
  # NOT flag Point.month(:wednesday) at the call site — it flags only
  # wrong-shaped arguments (as in compose/2 with a non-Point). We
  # chose the teaching runtime error over call-site flagging; drop
  # the fallback clauses to flip that choice. The runtime authority
  # stays validate_value!/2 inside new!/1.

  @doc "The year `n`: scope `:absolute`, grain class `:year`."
  @spec year(integer()) :: t()
  def year(n) when is_integer(n), do: new!(scope: :absolute, chain: [year: n])
  def year(other), do: bad_value!(:year, other)

  @doc "A month of the year: scope `:year`, grain class `:month`."
  @spec month(month()) :: t()
  def month(m) when m in @months, do: new!(scope: :year, chain: [month: m])
  def month(other), do: bad_value!(:month, other)

  @doc "An ISO week of the year (1..53): scope `:year`, grain class `:week`."
  @spec week(1..53) :: t()
  def week(n) when n in 1..53, do: new!(scope: :year, chain: [week: n])
  def week(other), do: bad_value!(:week, other)

  @doc """
  A day of the month: scope `:month`, grain class `:day`.

  Accepts a day number (`23`), a negative index from the month end
  (`-1` is the last day), or an ordinal weekday selector
  (`{:nth, 1, :wednesday}` is the first Wednesday).
  """
  @spec day(day_index() | nth_weekday()) :: t()
  def day(d) when d in 1..31 or d in -31..-1, do: new!(scope: :month, chain: [day: d])

  def day({:nth, n, wd} = d) when (n in 1..5 or n == -1) and wd in @weekdays do
    new!(scope: :month, chain: [day: d])
  end

  def day(other), do: bad_value!(:day, other)

  @doc "A day of the week: scope `:week`, grain class `:day`."
  @spec weekday(weekday()) :: t()
  def weekday(wd) when wd in @weekdays, do: new!(scope: :week, chain: [weekday: wd])
  def weekday(other), do: bad_value!(:weekday, other)

  @doc "A time of the day: scope `:day`, grain class `:time`."
  @spec time(Time.t()) :: t()
  def time(%Time{} = t), do: new!(scope: :day, chain: [time: t])
  def time(other), do: bad_value!(:time, other)

  # [claude-code]
  @doc """
  Compose two points: `outer` refined by `inner`.

  Defined exactly when the inner scope is a *plain* cycle whose class
  equals `grain_class(outer)`. The result keeps the outer scope and
  appends the inner chain:

      compose(year(2026), month(:may))
      #=> {:ok, %Point{scope: :absolute, chain: [year: 2026, month: :may]}}

      compose(month(:may), time(~T[15:00:00]))
      #=> {:error, %ComposeError{reason: :grain_gap, hint: "... Span.intersection ..."}}

  When the pair does not compose, the failure names why (see
  `ComposeError`):

  - `:grain_gap` — the inner nests inside the outer grain, but a unit
    level is free in the middle. The meaning is a set.
  - `:cross_cycle` — neither class nests in the other (weeks straddle
    month and year edges). The meaning is a set here too.
  - `:invalid` — the chain would run backward or repeat a unit.
  - `:anchored` — the inner scope is `{:every, k, cycle, anchor}`. It
    repeats once per *k* cycles, not once per cycle, and a chain has
    no place for that phase. Compose the plain points first, then
    re-scope the result with `every/3`. An every-scoped *outer* is
    fine: compose keeps the outer scope, phase included.

  The composed point keeps the overflow policy of the operand whose
  chain holds the day segment: overflow only means something where a
  day number sits, and a composed chain holds at most one day
  segment. When neither operand has one, the policy is inert and the
  outer's is kept.

  The `{:ok, _} | {:error, _}` shape is deliberate: the type checker
  presses call sites to handle the failure. Use `compose!/2` in
  pipelines that must raise.
  """
  @spec compose(t(), t()) :: {:ok, t()} | {:error, ComposeError.t()}
  def compose(%__MODULE__{} = outer, %__MODULE__{} = inner) do
    outer_grain = grain_class(outer)
    inner_scope = scope_class(inner)

    cond do
      # An {:every, ...} inner must fail before the class ladder:
      # class_of_scope/1 maps it to its base cycle, so the class test
      # alone would pass and the composed result (built from the
      # outer scope) would silently drop k and the anchor.
      match?({:every, _, _, _}, inner.scope) ->
        {:error, compose_error(:anchored, outer, inner)}

      inner_scope == outer_grain ->
        {:ok,
         new!(
           scope: outer.scope,
           chain: outer.chain ++ inner.chain,
           overflow: overflow_of(outer, inner)
         )}

      nests_in?(inner_scope, outer_grain) ->
        {:error, compose_error(:grain_gap, outer, inner)}

      nests_in?(outer_grain, inner_scope) ->
        {:error, compose_error(:invalid, outer, inner)}

      true ->
        {:error, compose_error(:cross_cycle, outer, inner)}
    end
  end

  # [claude-code]
  @doc "Like `compose/2` but raises the `ComposeError`."
  @spec compose!(t(), t()) :: t()
  def compose!(%__MODULE__{} = outer, %__MODULE__{} = inner) do
    case compose(outer, inner) do
      {:ok, point} -> point
      {:error, %ComposeError{} = error} -> raise error
    end
  end

  # [claude-code]
  @doc """
  Re-scope a cyclic point to every `k`-th instance of its cycle,
  counted from the instance that contains `anchor`.

      weekday(:wednesday) |> every(2, ~D[2026-01-07])
      #=> "every other Wednesday", in phase with Jan 7 2026

  The point's scope must be a plain cycle: an `:absolute` point does
  not repeat, and re-anchoring an `{:every, ...}` scope must restate
  it from the base cycle.
  """
  @spec every(t(), pos_integer(), Date.t()) :: t()
  def every(%__MODULE__{scope: scope} = point, k, %Date{} = anchor)
      when is_integer(k) and k > 0 do
    case scope do
      cycle when cycle in @cycles ->
        %{point | scope: {:every, k, cycle, anchor}}

      :absolute ->
        raise ArgumentError,
              "an :absolute point happens once, so it cannot repeat every " <>
                "#{k} cycles. Give a cyclic point such as Point.weekday(:wednesday)."

      {:every, old_k, cycle, old_anchor} ->
        raise ArgumentError,
              "this point already repeats every #{old_k} #{cycle}(s) from " <>
                "#{inspect(old_anchor)}. Nested anchors would hide which phase " <>
                "wins: restate the rhythm from the base #{inspect(cycle)} cycle."
    end
  end

  def every(%__MODULE__{}, k, anchor) do
    raise ArgumentError,
          "every/3 takes a positive integer k and a %Date{} anchor, " <>
            "got: k = #{inspect(k)}, anchor = #{inspect(anchor)}"
  end

  # [claude-code]
  @doc "The class of the point's finest segment (what the point names)."
  @spec grain_class(t()) :: grain_class()
  def grain_class(%__MODULE__{chain: chain}) do
    {unit, _value} = List.last(chain)
    unit_class(unit)
  end

  # [claude-code]
  @doc "The class of the point's scope unit (what the point repeats in)."
  @spec scope_class(t()) :: :absolute | grain_class()
  def scope_class(%__MODULE__{scope: scope}), do: class_of_scope(scope)

  # [claude-code] Vocabulary readers (added in step 3 for the set
  # layer). Months and weekdays have one canonical numbering
  # (january=1..december=12, monday=1..sunday=7, matching ISO and
  # Date.day_of_week/1). Zocam.Span does integer cell math with
  # these; keeping the mapping here keeps ONE definition of the
  # vocabulary, next to the atoms it numbers.

  @doc "The calendar number of a month atom: `:january` is 1, `:december` is 12."
  @spec month_number(month()) :: 1..12
  def month_number(m) when m in @months, do: Enum.find_index(@months, &(&1 == m)) + 1
  def month_number(other), do: bad_value!(:month, other)

  @doc "The month atom of a calendar number: 1 is `:january`, 12 is `:december`."
  @spec month_atom(1..12) :: month()
  def month_atom(n) when n in 1..12, do: Enum.at(@months, n - 1)
  def month_atom(other), do: bad_value!(:month, other)

  @doc "The ISO number of a weekday atom: `:monday` is 1, `:sunday` is 7."
  @spec weekday_number(weekday()) :: 1..7
  def weekday_number(wd) when wd in @weekdays, do: Enum.find_index(@weekdays, &(&1 == wd)) + 1
  def weekday_number(other), do: bad_value!(:weekday, other)

  @doc "The weekday atom of an ISO number: 1 is `:monday`, 7 is `:sunday`."
  @spec weekday_atom(1..7) :: weekday()
  def weekday_atom(n) when n in 1..7, do: Enum.at(@weekdays, n - 1)
  def weekday_atom(other), do: bad_value!(:weekday, other)

  # ── Composition ────────────────────────────────────────────────────

  # [claude-code] Strict nesting between grain classes: nests_in?(a, b)
  # is true when every instance of class a lies fully inside one
  # instance of class b. This relation is NOT the unit graph: the
  # graph says which units can sit under which in a chain (week sits
  # under year as a numbering, week 33), while nesting says which
  # cycles contain which (a week can straddle a month or a year edge,
  # so :week nests in nothing but :absolute). compose/2 uses nesting
  # to classify its failures.
  @spec nests_in?(:absolute | grain_class(), :absolute | grain_class()) :: boolean()
  defp nests_in?(class, :absolute) when class != :absolute, do: true
  defp nests_in?(:month, :year), do: true
  defp nests_in?(:day, outer) when outer in [:year, :month, :week], do: true
  defp nests_in?(:time, outer) when outer in [:year, :month, :week, :day], do: true
  defp nests_in?(_, _), do: false

  # [claude-code] The overflow policy of a composed point. The policy
  # travels with the day segment (the only segment it can act on); a
  # valid composed chain holds at most one. When neither operand has
  # one, the policy is inert, so the outer's is kept.
  @spec overflow_of(t(), t()) :: overflow()
  defp overflow_of(%__MODULE__{} = outer, %__MODULE__{} = inner) do
    if Keyword.has_key?(inner.chain, :day), do: inner.overflow, else: outer.overflow
  end

  # [claude-code] The three functions below build the ComposeError as
  # one unit: the struct, the reason sentence, and the repair hint.
  @spec compose_error(ComposeError.reason(), t(), t()) :: ComposeError.t()
  defp compose_error(reason, outer, inner) do
    hint = compose_hint(reason)

    %ComposeError{
      reason: reason,
      left: outer,
      right: inner,
      hint: hint,
      message:
        "cannot compose #{inspect(outer.chain)} (grain #{inspect(grain_class(outer))}) " <>
          "with #{inspect(inner.chain)} (repeats per #{inspect(scope_class(inner))}): " <>
          "#{compose_reason(reason)} #{hint}"
    }
  end

  @spec compose_reason(ComposeError.reason()) :: String.t()
  defp compose_reason(:grain_gap),
    do:
      "a unit level is free between the outer grain and the inner scope, " <>
        "so the meaning is a set of instants, not one point."

  defp compose_reason(:cross_cycle),
    do:
      "the two cycles do not nest (a week can straddle a month or a year edge), " <>
        "so no single chain holds both."

  defp compose_reason(:invalid),
    do: "the chain would run backward or repeat a unit."

  defp compose_reason(:anchored),
    do:
      "the inner point repeats every k-th cycle from an anchor, and a " <>
        "chain has no place for that phase."

  @spec compose_hint(ComposeError.reason()) :: String.t()
  defp compose_hint(reason) when reason in [:grain_gap, :cross_cycle] do
    "Build the set with Zocam.Span.intersection([Span.of(outer), Span.of(inner)])."
  end

  defp compose_hint(:invalid) do
    "Swap the operands, or drop the repeated unit."
  end

  defp compose_hint(:anchored) do
    "Compose the plain points first, then set the rhythm on the result with every/3."
  end

  # ── Validation ─────────────────────────────────────────────────────

  # [claude-code] The unit graph as data. children/1 answers one
  # question: which units can sit directly under a class? The chain
  # walk reads these edges here; compose/2 will read the same edges.
  @spec children(:absolute | grain_class()) :: [unit()]
  defp children(:absolute), do: [:year]
  defp children(:year), do: [:month, :week]
  defp children(:month), do: [:day]
  defp children(:week), do: [:weekday]
  defp children(:day), do: [:time]
  defp children(:time), do: []

  # [claude-code] The class of a unit: the span size the unit names.
  # :day and :weekday are different units with the same class. That
  # shared class is why "a Wednesday" can take a time of day.
  @spec unit_class(unit()) :: grain_class()
  defp unit_class(:year), do: :year
  defp unit_class(:month), do: :month
  defp unit_class(:week), do: :week
  defp unit_class(:day), do: :day
  defp unit_class(:weekday), do: :day
  defp unit_class(:time), do: :time

  # [claude-code] The class of a scope value. An {:every, k, cycle, _}
  # scope keeps the class of its base cycle: k changes the rhythm of
  # the instances, not their size.
  @spec class_of_scope(scope()) :: :absolute | grain_class()
  defp class_of_scope(:absolute), do: :absolute
  defp class_of_scope({:every, _k, cycle, %Date{}}), do: cycle
  defp class_of_scope(cycle) when cycle in @cycles, do: cycle

  # [claude-code] Scope and overflow checks for new!/1.
  @spec validate_scope!(term()) :: :ok
  defp validate_scope!(:absolute), do: :ok
  defp validate_scope!(cycle) when cycle in @cycles, do: :ok

  defp validate_scope!({:every, k, cycle, %Date{}})
       when is_integer(k) and k > 0 and cycle in @cycles,
       do: :ok

  defp validate_scope!(other) do
    raise ArgumentError,
          "not a scope: #{inspect(other)}. Give :absolute, a cycle in " <>
            "#{inspect(@cycles)}, or {:every, k, cycle, anchor_date}."
  end

  @spec validate_overflow!(term()) :: :ok
  defp validate_overflow!(policy) when policy in [:clamp, :skip], do: :ok

  defp validate_overflow!(other) do
    raise ArgumentError, "not an overflow policy: #{inspect(other)}. Give :clamp or :skip."
  end

  # [claude-code] The chain walk. It starts at the scope class and
  # follows the unit graph one edge at a time. Each step checks two
  # facts: the unit is a child of the level above it, and the value
  # is inside the unit's vocabulary.
  @spec validate_chain!(scope(), term()) :: :ok
  defp validate_chain!(scope, [_ | _] = chain), do: walk!(class_of_scope(scope), chain)

  defp validate_chain!(_scope, chain) do
    raise ArgumentError, "chain must be a non-empty keyword list, got: #{inspect(chain)}"
  end

  @spec walk!(:absolute | grain_class(), [term()]) :: :ok
  defp walk!(_class, []), do: :ok

  defp walk!(class, [{unit, value} | rest]) when is_atom(unit) do
    if unit not in children(class) do
      raise ArgumentError,
            "unit #{inspect(unit)} cannot sit directly under #{inspect(class)}: " <>
              "a chain descends the unit graph one level at a time, so the " <>
              "next unit must be one of #{inspect(children(class))}"
    end

    validate_value!(unit, value)
    walk!(unit_class(unit), rest)
  end

  defp walk!(_class, [segment | _rest]) do
    raise ArgumentError, "not a chain segment: #{inspect(segment)}"
  end

  # [claude-code] Vocabulary checks per unit: the runtime authority.
  # The constructor guards mirror these clauses for the type checker.
  @spec validate_value!(unit(), term()) :: :ok
  defp validate_value!(:year, n) when is_integer(n), do: :ok
  defp validate_value!(:month, m) when m in @months, do: :ok
  defp validate_value!(:week, n) when n in 1..53, do: :ok
  defp validate_value!(:day, n) when n in 1..31 or n in -31..-1, do: :ok

  defp validate_value!(:day, {:nth, n, wd}) when (n in 1..5 or n == -1) and wd in @weekdays,
    do: :ok

  defp validate_value!(:weekday, wd) when wd in @weekdays, do: :ok
  defp validate_value!(:time, %Time{}), do: :ok
  defp validate_value!(unit, value), do: bad_value!(unit, value)

  # [claude-code] One error text for a wrong unit value. The
  # constructors and the walk share it, so the message stays the same
  # on both paths.
  @spec bad_value!(unit(), term()) :: no_return()
  defp bad_value!(unit, value) do
    raise ArgumentError,
          "not a valid value for #{inspect(unit)}: #{inspect(value)}. Give #{expected(unit)}."
  end

  @spec expected(unit()) :: String.t()
  defp expected(:year), do: "an integer"
  defp expected(:month), do: "a full-name month atom such as :may"
  defp expected(:week), do: "an ISO week number in 1..53"

  defp expected(:day),
    do: "a day number in 1..31, a negative index in -31..-1, or {:nth, 1..5 | -1, weekday}"

  defp expected(:weekday), do: "a full-name weekday atom such as :wednesday"
  defp expected(:time), do: "a %Time{} struct"
end
